export { ModuleInstaller } from './installer.ts'
export {
  DEFAULT_INSTALL_LIMITS,
  DEFAULT_STALE_STAGING_AGE_MS,
  ModuleInstallerError,
  SimulatedInstallerCrash,
  type InstalledModuleState,
  type InstallLimits,
  type InstallPhase,
  type InstallProgress,
  type InstallRequest,
  type InstallResult,
  type InstallerFaultInjector,
  type InstallerFaultPoint,
  type ModuleInstallerErrorCode,
  type ModuleInstallerOptions,
  type ModuleUsageGuard,
  type ModuleUsageGuardLease,
  type RollbackResult,
  type UninstallRequest,
  type VerifiedArtifactDescriptor,
} from './types.ts'
